from pathlib import Path

ROOT = Path('ScannerApp')
MAIN = ROOT / 'app/src/main/java/com/indianequipments/usbscanner/MainActivity.kt'
PRINT = ROOT / 'app/src/main/java/com/indianequipments/usbscanner/PrintExActivity.kt'
RES = ROOT / 'app/src/main/res/drawable'
RES.mkdir(parents=True, exist_ok=True)


def replace(path, old, new):
    s = path.read_text(encoding='utf-8')
    if old in s:
        path.write_text(s.replace(old, new, 1), encoding='utf-8')

# Main bottom navigation uses the approved supplied icon set.
replace(MAIN, '''        navButton("⌂", "Home", 0)\n        navButton("◎", "Studio", 1)\n        navButton("▦", "Library", 2)\n        navButton("▣", "Printex", 3)''', '''        navButton(R.drawable.ic_home, "Home", 0)\n        navButton(R.drawable.ic_studio, "Studio", 1)\n        navButton(R.drawable.ic_library, "Library", 2)\n        navButton(R.drawable.ic_printer, "Printex", 3)''')
replace(MAIN, '''    private fun navButton(icon: String, label: String, tab: Int) {\n        val holder = LinearLayout(this).apply {\n            orientation = LinearLayout.VERTICAL\n            gravity = Gravity.CENTER\n            isClickable = true\n            isFocusable = true\n            setPadding(0,dp(2),0,dp(2))\n            setOnClickListener { renderTab(tab) }\n        }\n        holder.addView(TextView(this).apply {\n            text = icon\n            gravity = Gravity.CENTER\n            textSize = 20f\n            typeface = Typeface.DEFAULT_BOLD\n            setTextColor(if (tab == currentTab) Color.rgb(85,160,255) else Color.rgb(125,140,160))\n        })''', '''    private fun navButton(iconRes: Int, label: String, tab: Int) {\n        val holder = LinearLayout(this).apply {\n            orientation = LinearLayout.VERTICAL\n            gravity = Gravity.CENTER\n            isClickable = true\n            isFocusable = true\n            setPadding(0,dp(2),0,dp(2))\n            setOnClickListener { renderTab(tab) }\n        }\n        holder.addView(ImageView(this).apply {\n            setImageResource(iconRes)\n            layoutParams = LinearLayout.LayoutParams(dp(28), dp(28))\n            scaleType = ImageView.ScaleType.CENTER_INSIDE\n            alpha = if (tab == currentTab) 1f else 0.72f\n        })''')

# Printex quick-action icons.
replace(PRINT, 'quick.addView(tile("▦","Library") { chooseDocument() }, weight())', 'quick.addView(tile(R.drawable.ic_library,"Library") { openScannerTab(2) }, weight())')
replace(PRINT, 'quick.addView(tile("▦","Library") { Toast.makeText(this,"Library documents can be selected from Files",Toast.LENGTH_SHORT).show(); chooseDocument() }, weight())', 'quick.addView(tile(R.drawable.ic_library,"Library") { openScannerTab(2) }, weight())')
replace(PRINT, 'quick.addView(tile("▣","Files") { chooseDocument() }, weight())', 'quick.addView(tile(R.drawable.ic_files,"Files") { chooseDocument() }, weight())')
replace(PRINT, 'quick.addView(tile("▧","Gallery") { chooseImage() }, weight())', 'quick.addView(tile(R.drawable.ic_gallery,"Gallery") { chooseImage() }, weight())')
replace(PRINT, 'quick.addView(tile("◎","Scan") { startActivity(Intent(this,MainActivity::class.java)) }, weight())', 'quick.addView(tile(R.drawable.ic_scan,"Scan") { openScannerTab(1) }, weight())')
replace(PRINT, 'quick.addView(tile("◎", "Scan") { openScannerTab(1) }, weight())', 'quick.addView(tile(R.drawable.ic_scan, "Scan") { openScannerTab(1) }, weight())')

# Printex bottom navigation icons.
replace(PRINT, 'nav.addView(navButton("⌂", "Home") { openScannerTab(0) }, navWeight())\n        nav.addView(navButton("◎", "Studio") { openScannerTab(1) }, navWeight())\n        nav.addView(navButton("▦", "Library") { openScannerTab(2) }, navWeight())\n        nav.addView(navButton("▣", "Printex") { }, navWeight())', 'nav.addView(navButton(R.drawable.ic_home, "Home") { openScannerTab(0) }, navWeight())\n        nav.addView(navButton(R.drawable.ic_studio, "Studio") { openScannerTab(1) }, navWeight())\n        nav.addView(navButton(R.drawable.ic_library, "Library") { openScannerTab(2) }, navWeight())\n        nav.addView(navButton(R.drawable.ic_printer, "Printex") { }, navWeight())')
replace(PRINT, 'private fun navButton(icon:String,label:String,click:()->Unit)=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; gravity=Gravity.CENTER; setOnClickListener{click()}; addView(TextView(this@PrintExActivity).apply{text=icon;textSize=20f;gravity=Gravity.CENTER;setTextColor(if(label=="Printex") BLUE else MUTED)}); addView(TextView(this@PrintExActivity).apply{text=label;textSize=11f;gravity=Gravity.CENTER;setTextColor(if(label=="Printex") BLUE else MUTED)}) }', 'private fun navButton(iconRes:Int,label:String,click:()->Unit)=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; gravity=Gravity.CENTER; setOnClickListener{click()}; addView(ImageView(this@PrintExActivity).apply{setImageResource(iconRes);layoutParams=LinearLayout.LayoutParams(dp(28),dp(28));scaleType=ImageView.ScaleType.CENTER_INSIDE;alpha=if(label=="Printex")1f else .72f}); addView(TextView(this@PrintExActivity).apply{text=label;textSize=11f;gravity=Gravity.CENTER;setTextColor(if(label=="Printex") BLUE else MUTED)}) }')

# Tile renderer accepts a drawable resource instead of a text glyph.
replace(PRINT, 'private fun tile(i:String,s:String,a:()->Unit)=Button(this).apply{text="$i\\n$s";textSize=10f;setTextColor(Color.rgb(215,225,238));isAllCaps=false;background=rounded(Color.rgb(18,25,36),14);setOnClickListener{a()};minHeight=0;minimumHeight=0}', 'private fun tile(iconRes:Int,s:String,a:()->Unit)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(dp(4),dp(7),dp(4),dp(7));background=rounded(Color.rgb(18,25,36),14);setOnClickListener{a()};addView(ImageView(this@PrintExActivity).apply{setImageResource(iconRes);layoutParams=LinearLayout.LayoutParams(dp(28),dp(28));scaleType=ImageView.ScaleType.CENTER_INSIDE});addView(TextView(this@PrintExActivity).apply{text=s;textSize=10f;gravity=Gravity.CENTER;setTextColor(Color.rgb(215,225,238));setPadding(0,dp(3),0,0)})}')

icons = {
'ic_library.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#224A85" android:pathData="M7,16 L17,9 L55,18 L47,25 Z"/><path android:fillColor="#2E73C9" android:pathData="M7,16 L47,25 L47,53 L7,44 Z"/><path android:fillColor="#63A7FF" android:pathData="M17,9 L55,18 L55,46 L47,53 L47,25 L17,18 Z"/><path android:fillColor="#FFFFFF" android:pathData="M17,23 L43,29 L43,32 L17,26 Z"/><path android:fillColor="#FFFFFF" android:pathData="M17,30 L43,36 L43,39 L17,33 Z"/></vector>''',
'ic_files.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#3978FF" android:pathData="M7,18 Q7,12 13,12 L28,12 L34,18 L53,18 Q57,18 57,23 L57,49 Q57,54 52,54 L12,54 Q7,54 7,49 Z"/><path android:fillColor="#4B91FF" android:pathData="M10,25 L54,25 L50,50 L14,50 Z"/></vector>''',
'ic_gallery.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#4A8FFF" android:pathData="M9,10 Q9,6 13,6 L51,6 Q55,6 55,10 L55,54 Q55,58 51,58 L13,58 Q9,58 9,54 Z"/><path android:fillColor="#B7CEF5" android:pathData="M14,47 L25,34 L33,42 L39,35 L50,48 Z"/><path android:fillColor="#FFFFFF" android:pathData="M40,18 A5,5 0,1 0,40.1,18"/></vector>''',
'ic_scan.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#D8E4F7" android:pathData="M12,8 L50,8 L50,43 L12,43 Z"/><path android:fillColor="#000000" android:pathData="M22,14 L27,14 L27,19 L22,19 Z M30,14 L35,14 L35,19 L30,19 Z M38,14 L43,14 L43,19 L38,19 Z M22,22 L27,22 L27,27 L22,27 Z M30,22 L35,22 L35,27 L30,27 Z M38,22 L43,22 L43,27 L38,27 Z M22,30 L27,30 L27,35 L22,35 Z M30,30 L35,30 L35,35 L30,35 Z M38,30 L43,30 L43,35 L38,35 Z"/><path android:fillColor="#2F67C0" android:pathData="M7,47 L57,47 L57,54 L7,54 Z"/></vector>''',
'ic_studio.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#168FF5" android:pathData="M9,35 L18,20 L26,22 L24,14 L35,9 L45,18 L55,13 L57,25 L49,33 L54,42 L43,50 L33,44 L23,53 L14,46 Z"/><path android:fillColor="#55C71F" android:pathData="M12,31 L22,24 L27,29 L19,38 Z M33,36 L42,27 L48,33 L40,43 Z"/><path android:fillColor="#FFD34D" android:pathData="M8,30 L56,30 L56,35 L8,35 Z"/></vector>''',
'ic_home.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#FFFFFF" android:pathData="M8,29 L32,8 L56,29 L52,34 L52,55 L12,55 L12,34 Z"/><path android:fillColor="#287CC9" android:pathData="M27,55 L27,39 L37,39 L37,55 Z"/></vector>''',
'ic_printer.xml': '''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#2F67C0" android:pathData="M17,20 L47,20 L47,31 L17,31 Z"/><path android:fillColor="#3978FF" android:pathData="M11,27 L53,27 Q58,27 58,33 L58,46 Q58,51 53,51 L11,51 Q6,51 6,46 L6,33 Q6,27 11,27 Z"/><path android:fillColor="#D8E4F7" android:pathData="M17,39 L47,39 L47,57 L17,57 Z"/><path android:fillColor="#FFD34D" android:pathData="M14,34 A3,3 0,1 0,14.1,34"/></vector>'''
}
for name, content in icons.items():
    (RES / name).write_text(content, encoding='utf-8')
print('Applied approved Scanner/Printex icons')
