package com.indianequipments.usbscanner
import android.app.*
import android.content.*
import android.graphics.*
import android.graphics.pdf.PdfRenderer
import android.hardware.usb.*
import android.net.Uri
import android.os.*
import android.print.*
import android.view.*
import android.widget.*
import java.io.*
import kotlin.math.*

class PrintExActivity:Activity(){
 private lateinit var preview:ImageView;private lateinit var name:TextView;private lateinit var pages:TextView;private lateinit var status:TextView
 private var file:File?=null;private var mime="application/pdf";private var count=0;private var page=0;private var bmp:Bitmap?=null
 private var copies=1;private var color="Black & White";private var paper="A4";private var orient="Portrait";private var duplex="Off";private var scale="Fit to Page";private var pps=1;private var range="All";private var quality="High";private var margins="Default";private var reverse=false;private var bright=0;private var contrast=100;private var autoRotate=true
 private val BG=Color.rgb(8,12,20);private val PANEL=Color.rgb(15,21,31);private val BLUE=Color.rgb(110,165,255);private val MUTED=Color.rgb(145,160,180)
 override fun onCreate(b:Bundle?){super.onCreate(b);window.statusBarColor=BG;window.navigationBarColor=BG;ui();handle(intent)}
 override fun onResume(){super.onResume();if(::status.isInitialized)refreshStatus()}
 private fun ui(){val shell=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(BG)};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(42),dp(18),dp(14))};shell.addView(ScrollView(this).apply{addView(root)},LinearLayout.LayoutParams(-1,0,1f));shell.addView(nav(),LinearLayout.LayoutParams(-1,dp(78)));setContentView(shell)
  val h=row();h.addView(txt("PRINTEX",28,Color.WHITE,true),LinearLayout.LayoutParams(0,-2,1f));h.addView(txt("⋮",28,MUTED,false).apply{setOnClickListener{menu()}});root.addView(h);root.addView(txt("PROFESSIONAL PRINT STUDIO",11,BLUE,true).apply{setPadding(0,dp(3),0,dp(14))})
  val st=card();st.addView(txt("PRINTER STATUS",11,MUTED,false));status=txt("",18,Color.WHITE,true);st.addView(status);st.addView(txt("Live USB printer detection • print settings apply to print job",12,MUTED,false));root.addView(st,margin(0,10));refreshStatus()
  root.addView(btn("▣  SELECT DOCUMENT"){pick(false)},margin(0,10));val q=row();q.addView(tile("▦","Library"){pick(false)},weight());q.addView(tile("▣","Files"){pick(false)},weight());q.addView(tile("▧","Gallery"){pick(true)},weight());q.addView(tile("◎","Scan"){startActivity(Intent(this,MainActivity::class.java))},weight());root.addView(q,margin(0,12))
  root.addView(section("DOCUMENT PREVIEW"));val pc=card();preview=ImageView(this).apply{scaleType=ImageView.ScaleType.FIT_CENTER;setBackgroundColor(Color.rgb(18,24,34));setPadding(dp(10),dp(10),dp(10),dp(10));setOnClickListener{viewer()}};pc.addView(preview,LinearLayout.LayoutParams(-1,dp(310)));val pr=row();pr.addView(sbtn("‹"){show(page-1)},LinearLayout.LayoutParams(dp(52),dp(42)));pages=txt("Page 0 / 0",12,MUTED,false).apply{gravity=Gravity.CENTER};pr.addView(pages,LinearLayout.LayoutParams(0,dp(42),1f));pr.addView(sbtn("›"){show(page+1)},LinearLayout.LayoutParams(dp(52),dp(42)));pc.addView(pr);name=txt("No document selected",16,Color.WHITE,true);pc.addView(name);pc.addView(txt("Touch to open • pinch to zoom • drag to inspect",11,MUTED,false));root.addView(pc,margin(0,10))
  root.addView(section("PRINT SETTINGS"));val set=card();row(set,"Printer",printerName()){printerChooser()};row(set,"Paper Size",paper){choose("Paper Size",arrayOf("A4","A5","A3","Letter","Legal")){paper=it;uiKeep()}};row(set,"Orientation",orient){choose("Orientation",arrayOf("Portrait","Landscape","Auto")){orient=it;uiKeep()}};row(set,"Color Mode",color){choose("Color Mode",arrayOf("Color","Grayscale","Black & White")){color=it;uiKeep()}};row(set,"Copies",copies.toString()){copiesDialog()};row(set,"Pages",range){pagesDialog()};row(set,"Scale",scale){choose("Scale",arrayOf("Fit to Page","Actual Size","Fill Page","Shrink Oversized","Custom 50%","Custom 75%","Custom 125%","Custom 150%")){scale=it;uiKeep()}};row(set,"Duplex",duplex){choose("Duplex",arrayOf("Off","Long Edge","Short Edge")){duplex=it;uiKeep()}};row(set,"Pages / Sheet",pps.toString()){choose("Pages / Sheet",arrayOf("1","2","4","6","9","16")){pps=it.toInt();uiKeep()}};row(set,"Print Quality",quality){choose("Print Quality",arrayOf("Draft","Normal","High")){quality=it;uiKeep()}};row(set,"Margins",margins){choose("Margins",arrayOf("Default","Narrow","None")){margins=it;uiKeep()}};row(set,"Brightness",bright.toString()){slider("Brightness",-100,100,bright){bright=it;uiKeep()}};row(set,"Contrast","$contrast%"){slider("Contrast",50,200,contrast){contrast=it;uiKeep()}};row(set,"Auto Rotate",if(autoRotate)"On" else "Off"){autoRotate=!autoRotate;uiKeep()};row(set,"Reverse Order",if(reverse)"On" else "Off"){reverse=!reverse;uiKeep()};root.addView(set,margin(0,10));root.addView(btn("✦  SMART PRINT"){smart()},margin(0,8));root.addView(btn("▣  PRINT DOCUMENT"){print()},margin(0,8))
 }
 private fun txt(s:String,z:Float,c:Int,b:Boolean)=TextView(this).apply{text=s;textSize=z;setTextColor(c);if(b)setTypeface(null,1)}
 private fun row()=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL}
 private fun card()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(14));background=round(PANEL,18)}
 private fun section(s:String)=txt(s,11,MUTED,true).apply{setPadding(dp(2),dp(4),0,dp(7))}
 private fun btn(s:String,a:()->Unit)=Button(this).apply{text=s;textSize=13f;setTypeface(null,1);setTextColor(Color.WHITE);background=round(Color.rgb(34,94,215),18);setOnClickListener{a()}}
 private fun sbtn(s:String,a:()->Unit)=Button(this).apply{text=s;textSize=20f;setTextColor(Color.WHITE);background=round(PANEL,14);setOnClickListener{a()}}
 private fun tile(i:String,s:String,a:()->Unit)=Button(this).apply{text="$i\n$s";textSize=10f;setTextColor(Color.WHITE);background=round(PANEL,14);setOnClickListener{a()}}
 private fun weight()=LinearLayout.LayoutParams(0,dp(62),1f).apply{setMargins(dp(3),0,dp(3),0)}
 private fun margin(t:Int,b:Int)=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(t),0,dp(b))}
 private fun round(c:Int,r:Int)=android.graphics.drawable.GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat();setStroke(dp(1),Color.rgb(28,38,52))}
 private fun dp(v:Int)=(v*resources.displayMetrics.density).roundToInt()
 private fun row(p:LinearLayout,l:String,v:String,a:()->Unit){val r=row().apply{setPadding(0,dp(6),0,dp(6));setOnClickListener{a()}};r.addView(txt(l,13,Color.rgb(205,215,230),false),LinearLayout.LayoutParams(0,dp(44),1f));r.addView(txt("$v  ›",12,Color.WHITE,false));p.addView(r);p.addView(View(this).apply{setBackgroundColor(Color.rgb(28,38,52))},LinearLayout.LayoutParams(-1,1))}
 private fun pick(image:Boolean){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type=if(image)"image/*" else "*/*";putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/jpeg","image/png","image/webp"));addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)},REQ)}
 override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(r==REQ&&c==RESULT_OK)d?.data?.let{import(it)}}
 private fun handle(i:Intent?){val u=i?.data?:i?.getParcelableExtra<Uri>(Intent.EXTRA_STREAM);u?.let{import(it)}}
 private fun import(u:Uri){val t=contentResolver.getType(u) ?: "application/octet-stream";mime=if(t.contains("pdf",true)||u.toString().contains(".pdf",true))"application/pdf" else t;val f=File(cacheDir,"printex_${System.currentTimeMillis()}.${if(mime=="application/pdf")"pdf" else "img"}");try{contentResolver.openInputStream(u).use{input->FileOutputStream(f).use{out->input!!.copyTo(out)}};file?.delete();file=f;name.text=u.lastPathSegment?.substringAfterLast('/')?:"Selected document";page=0;load()}catch(e:Throwable){Toast.makeText(this,"Import failed: ${e.message}",Toast.LENGTH_LONG).show()}}
 private fun load(){bmp?.let{if(!it.isRecycled)it.recycle()};bmp=null;if(mime=="application/pdf"){try{ParcelFileDescriptor.open(file!!,ParcelFileDescriptor.MODE_READ_ONLY).use{p->PdfRenderer(p).use{count=it.pageCount}};show(0)}catch(_:Throwable){count=0}}else{bmp=BitmapFactory.decodeFile(file!!.absolutePath);count=if(bmp!=null)1 else 0;preview.setImageBitmap(bmp);pages.text="Page 1 / 1"}}
 private fun show(i:Int){if(file==null||count<1)return;page=i.coerceIn(0,count-1);if(mime=="application/pdf")try{bmp?.let{if(!it.isRecycled)it.recycle()};bmp=render(file!!,page,2.5f);preview.setImageBitmap(bmp)}catch(_:Throwable){}else preview.setImageBitmap(bmp);pages.text="Page ${page+1} / $count"}
 private fun render(f:File,i:Int,s:Float):Bitmap{ParcelFileDescriptor.open(f,ParcelFileDescriptor.MODE_READ_ONLY).use{p->PdfRenderer(p).use{r->r.openPage(i).use{pg->val b=Bitmap.createBitmap(max(900,(pg.width*s).roundToInt()),max(1200,(pg.height*s).roundToInt()),Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);pg.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);return b}}}}
 private fun viewer(){val f=file?:run{Toast.makeText(this,"Select a document first",Toast.LENGTH_SHORT).show();return};val d=Dialog(this,android.R.style.Theme_DeviceDefault_NoActionBar_Fullscreen);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(BG);setPadding(dp(8),dp(30),dp(8),dp(8))};box.addView(txt("‹  DOCUMENT PREVIEW",18,Color.WHITE,true).apply{setPadding(dp(8),dp(8),0,dp(8));setOnClickListener{d.dismiss()}});val z=ZoomView(this);z.setImageBitmap(if(mime=="application/pdf")render(f,page,4f)else bmp);box.addView(z,LinearLayout.LayoutParams(-1,0,1f));z.post{z.reset()};val nav=row();nav.addView(sbtn("‹"){if(page>0){page--;z.setImageBitmap(if(mime=="application/pdf")render(f,page,4f)else bmp);z.post{z.reset()}}});nav.addView(txt("Page ${page+1} / $count",13,MUTED,false),LinearLayout.LayoutParams(0,dp(48),1f).apply{gravity=Gravity.CENTER});nav.addView(sbtn("›"){if(page<count-1){page++;z.setImageBitmap(if(mime=="application/pdf")render(f,page,4f)else bmp);z.post{z.reset()}}});box.addView(nav);d.setContentView(box);d.show()}
 private fun choose(t:String,a:Array<String>,done:(String)->Unit){AlertDialog.Builder(this).setTitle(t).setItems(a){_,i->done(a[i])}.show()}
 private fun slider(t:String,minV:Int,maxV:Int,start:Int,done:(Int)->Unit){val s=SeekBar(this).apply{max=maxV-minV;progress=start.coerceIn(minV,maxV)-minV};AlertDialog.Builder(this).setTitle(t).setView(s).setPositiveButton("Apply"){_,_->done(s.progress+minV)}.setNegativeButton("Cancel",null).show()}
 private fun copiesDialog(){val e=EditText(this).apply{inputType=2;setText(copies.toString())};AlertDialog.Builder(this).setTitle("Copies").setView(e).setPositiveButton("Apply"){_,_->copies=(e.text.toString().toIntOrNull()?:1).coerceIn(1,99);uiKeep()}.setNegativeButton("Cancel",null).show()}
 private fun pagesDialog(){choose("Pages",arrayOf("All","Current","Odd","Even","Custom Range")){if(it=="Custom Range"){val e=EditText(this);AlertDialog.Builder(this).setTitle("Custom Range").setView(e).setPositiveButton("Apply"){_,_->range=e.text.toString();uiKeep()}.show()}else{range=it;uiKeep()}}}
 private fun uiKeep(){val f=file;ui();if(f!=null&&f.exists()){file=f;load()}}
 private fun smart(){if(file==null){Toast.makeText(this,"Select a document first",Toast.LENGTH_SHORT).show();return};paper="A4";scale="Fit to Page";quality="High";autoRotate=true;uiKeep();Toast.makeText(this,"Smart Print optimized",Toast.LENGTH_SHORT).show()}
 private fun print(){val f=file?:run{Toast.makeText(this,"Select a document first",Toast.LENGTH_SHORT).show();return};val pm=getSystemService(PRINT_SERVICE) as PrintManager;val b=PrintAttributes.Builder().setMediaSize(if(orient=="Landscape")PrintAttributes.MediaSize.ISO_A4.asLandscape() else PrintAttributes.MediaSize.ISO_A4).setColorMode(if(color=="Color")PrintAttributes.COLOR_MODE_COLOR else PrintAttributes.COLOR_MODE_MONOCHROME).setMinMargins(if(margins=="None")PrintAttributes.Margins.NO_MARGINS else PrintAttributes.Margins(300,300,300,300));if(Build.VERSION.SDK_INT>=23)b.setDuplexMode(if(duplex=="Long Edge")PrintAttributes.DUPLEX_MODE_LONG_EDGE else if(duplex=="Short Edge")PrintAttributes.DUPLEX_MODE_SHORT_EDGE else PrintAttributes.DUPLEX_MODE_NONE);pm.print("Printex • ${f.nameWithoutExtension}",Adapter(f),b.build())}
 private inner class Adapter(private val f:File):PrintDocumentAdapter(){override fun onLayout(o:PrintAttributes?,n:PrintAttributes,c:CancellationSignal,cb:LayoutResultCallback,e:Bundle?){if(c.isCanceled){cb.onLayoutCancelled();return};cb.onLayoutFinished(PrintDocumentInfo.Builder(f.name).setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(count.coerceAtLeast(1)).build(),true)};override fun onWrite(r:Array<PageRange>,d:ParcelFileDescriptor,c:CancellationSignal,cb:WriteResultCallback){try{FileInputStream(f).use{input->ParcelFileDescriptor.AutoCloseOutputStream(d).use{out->input.copyTo(out)}};cb.onWriteFinished(arrayOf(PageRange.ALL_PAGES))}catch(e:Throwable){cb.onWriteFailed(e.message)}}}
 private fun printerName():String{val d=usb();return d?.let{"${it.productName?:it.deviceName} Connected"}?:"Printer is not connected"}
 private fun refreshStatus(){val d=usb();status.text=d?.let{"●  ${it.productName?:it.deviceName} Connected"}?:"Printer is not connected";status.setTextColor(if(d==null)Color.rgb(255,170,90) else Color.rgb(75,220,145))}
 private fun usb():UsbDevice?{val m=getSystemService(Context.USB_SERVICE) as UsbManager;return m.deviceList.values.firstOrNull{it.deviceClass==7||(0 until it.interfaceCount).any{n->it.getInterface(n).interfaceClass==7}}}
 private fun printerChooser(){Toast.makeText(this,printerName(),Toast.LENGTH_SHORT).show()}
 private fun menu(){AlertDialog.Builder(this).setTitle("Printex").setItems(arrayOf("Printer Management","Print Queue","Print History","Printer Diagnostics","Default Settings")){_,i->when(i){0->printerChooser();1->Toast.makeText(this,"Print queue is managed by Android print service",Toast.LENGTH_SHORT).show();2->Toast.makeText(this,"Print history is available after print jobs",Toast.LENGTH_SHORT).show();3->Toast.makeText(this,printerName(),Toast.LENGTH_SHORT).show();4->Toast.makeText(this,"A4 • Portrait • $color • $duplex",Toast.LENGTH_SHORT).show()}}.show()}
 private fun nav():View{val n=row();n.background=round(PANEL,20);arrayOf("⌂" to "Home","◎" to "Studio","▦" to "Library","▣" to "Printex").forEach{(i,s)->n.addView(LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;addView(txt(i,20,if(s=="Printex")BLUE else MUTED,false));addView(txt(s,11,if(s=="Printex")BLUE else MUTED,false));setOnClickListener{if(s!="Printex")startActivity(Intent(this@PrintExActivity,MainActivity::class.java))}},LinearLayout.LayoutParams(0,-1,1f))};return n}
 private class ZoomView(c:Context):ImageView(c){var sc=1f;var lx=0f;var ly=0f;var moving=false;val m=Matrix();val sd=ScaleGestureDetector(c,object:ScaleGestureDetector.SimpleOnScaleGestureListener(){override fun onScale(d:ScaleGestureDetector):Boolean{sc=(sc*d.scaleFactor).coerceIn(1f,10f);m.postScale(d.scaleFactor,d.scaleFactor,d.focusX,d.focusY);imageMatrix=m;return true}});init{scaleType=ScaleType.MATRIX;setOnTouchListener{_,e->sd.onTouchEvent(e);when(e.actionMasked){MotionEvent.ACTION_DOWN->{lx=e.x;ly=e.y;moving=true};MotionEvent.ACTION_MOVE->{if(moving&&!sd.isInProgress&&sc>1){m.postTranslate(e.x-lx,e.y-ly);imageMatrix=m;lx=e.x;ly=e.y}};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{moving=false}};true}};fun reset(){sc=1f;m.reset();val d=drawable;if(d!=null&&width>0&&height>0){val sx=width.toFloat()/d.intrinsicWidth;val sy=height.toFloat()/d.intrinsicHeight;val s=min(sx,sy);m.setScale(s,s);m.postTranslate((width-d.intrinsicWidth*s)/2f,(height-d.intrinsicHeight*s)/2f)}imageMatrix=m}}
}
